In [2]:
import numpy as np

In [4]:
angulo_cero_noventa = np.array((0,30,45,60,90))
angulo_cero_noventa

array([ 0, 30, 45, 60, 90])

In [5]:
np.pi

3.141592653589793

In [8]:
# a radianes
angulo_radianes = angulo_cero_noventa * np.pi /180
angulo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [10]:
# sen, cos
np.sin(angulo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [11]:
np.cos(angulo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [12]:
np.tan(angulo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [17]:
# arreglos randómicos
arreglo_random_diez = np.random.rand(10)
arreglo_random_diez = arreglo_random_diez * 10
arreglo_random_diez

array([1.20686655, 2.51954262, 7.43889109, 8.49057174, 1.04846343,
       7.24794823, 8.28876905, 1.20080475, 2.09140276, 0.09456193])

In [22]:
arreglo_random_diez1 = np.random.randint(-10,1000,10) # (menor, tope, tamaño)
arreglo_random_diez1

array([879, 266, 345, 740, 540,  91, 665, 574, 776, 102])

In [25]:
np.random.randint(10) # desde el 0 al 10

8

In [26]:
arreglo_random_diez1.mean() # media

497.8

In [27]:
np.median(arreglo_random_diez1) # mediana

557.0

In [29]:
np.std(arreglo_random_diez1) # desviacion estándar

267.60710005528625

In [30]:
np.var(arreglo_random_diez1) # Varianza

71613.56