## Reshaping

In [1]:
import numpy as np

In [2]:
paises_uno = ('Ecuador','USA','Cuba','Venezuela')

In [3]:
paises_dos = ('Brasil','China','Japon','Mexico')

In [5]:
arreglo_paises_2d = np.array([paises_uno,paises_dos])

In [6]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [8]:
#ver num de dimensines de arreglo numpy
arreglo_paises_2d.shape # -> 2 dimensiones, cada dimension con 4 elementos

(2, 4)

In [9]:
arreglo_paises_2d.flatten()

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brasil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [11]:
arreglo_paises_2d.flatten().shape # cambia a una sola dimnesion

(8,)

In [12]:
arreglo_paises_2d.flatten().reshape(2,2,2)

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brasil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [14]:
# En reshaping
arreglo_paises_2d.flatten().reshape(4,-1) # -1 -> lo que calce, lo que logre llenar

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brasil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [15]:
arreglo_paises_2d.flatten().reshape(-1,2) 

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brasil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [16]:
arreglo_paises_2d.flatten().reshape(2,2,-1) 

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brasil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [18]:
# Transpuesta
arreglo_paises_2d.T

array([['Ecuador', 'Brasil'],
       ['USA', 'China'],
       ['Cuba', 'Japon'],
       ['Venezuela', 'Mexico']], dtype='<U9')

In [19]:
arreglo_paises_2d.T.shape

(4, 2)

In [20]:
arreglo_paises_2d.T.flatten()

array(['Ecuador', 'Brasil', 'USA', 'China', 'Cuba', 'Japon', 'Venezuela',
       'Mexico'], dtype='<U9')

### splitting

In [22]:
# vertical y horizontal
arreglo_paises = arreglo_paises_2d.flatten()

In [23]:
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brasil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [24]:
np.split(arreglo_paises,2) # devuelve el arreglo dividido en 2 partes

[array(['Ecuador', 'USA', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brasil', 'China', 'Japon', 'Mexico'], dtype='<U9')]

In [25]:
np.split(arreglo_paises,4) 

[array(['Ecuador', 'USA'], dtype='<U9'),
 array(['Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brasil', 'China'], dtype='<U9'),
 array(['Japon', 'Mexico'], dtype='<U9')]

In [26]:
arreglo = np.arange(12)

In [27]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.split(arreglo,6)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [29]:
np.split(arreglo,[1,3,5,7,8])# se puede seleccionar los indices en donde se desea cortar (split)

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([ 8,  9, 10, 11])]

In [30]:
# Se tiene también el horizontal split y vertical split
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brasil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [32]:
#horizontal
np.hsplit(arreglo_paises,2)

[array(['Ecuador', 'USA', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brasil', 'China', 'Japon', 'Mexico'], dtype='<U9')]

In [33]:
# split normal
np.split(arreglo_paises,2)

[array(['Ecuador', 'USA', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brasil', 'China', 'Japon', 'Mexico'], dtype='<U9')]

In [34]:
np.split(arreglo_paises_2d,2)

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [35]:
# vertical split, es muy similar al split normal
np.vsplit(arreglo_paises_2d,2)

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [36]:
arr1, arr2, arr3, arr4 = np.hsplit(arreglo_paises_2d,4) # guardar el horizontal split en variables

In [38]:
type(np.hsplit(arreglo_paises_2d,4)) # >> entonces, resulta que es una lista

list

In [39]:
x1,x2,x3 = [1,2,3]

In [40]:
x1

1

In [41]:
arr1

array([['Ecuador'],
       ['Brasil']], dtype='<U9')

In [42]:
x1 = x2 = x3 = 1

In [44]:
x1 = x1 +1

In [45]:
x1

2

In [46]:
x2

1