## Índices

In [2]:
import numpy as np

In [3]:
numeros = np.arange(11)**2

In [4]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [5]:
indices = [2,3,5]

In [6]:
numeros[indices]

array([ 4,  9, 25])

In [8]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Plàtano','Granadilla','Sandìa']
])

In [9]:
arreglo_frutas.shape

(3, 4)

In [11]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])
arreglo_filas

array([[0, 0],
       [1, 1],
       [2, 2]])

In [12]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])
arreglo_columnas

array([[1, 3],
       [1, 2],
       [0, 2]])

In [14]:
arreglo_frutas[arreglo_filas, arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [15]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Plàtano', 'Granadilla', 'Sandìa']], dtype='<U10')

In [17]:
# tomar los dos ultimos de cada fila
arreglo_filas1 = np.array([
    [0,0],
    [1,1],
    [2,2],
])
arreglo_columnas1 = np.array([
    [2,3],
    [2,3],
    [2,3],
])
arreglo_frutas[arreglo_filas1,arreglo_columnas1]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandìa']], dtype='<U10')

In [42]:
# crear un arreglo de 4 x 3 x 2 (12 elementos más)
# seleccionar al primero y el último
arreglo_frutas2d = np.array([
    ['Piña','Fresa','Manzana','Achotillo','Pera','Kiwi'],
    ['Aguacate','Arándano','Uva','Grosella','Naranja','Pepino'],
    ['Frutilla','Ciruela','Plàtano','Coco','Granadilla','Guaba'],
    ['Melon','Limon','Papaya','Mango','Sandìa','Cereza']
])
arreglo_frutas2d.shape
arreglo_frutas3d = arreglo_frutas2d
arreglo_frutas3d.shape = 4,3,2
dim1 = np.array([
    [0,0,0]
])

dim2 = np.array([
    [0,0,1]
])
dim3 = np.array([
    [0,1,0]
])
print(arreglo_frutas3d)
arreglo_frutas3d[dim1,dim2,dim3]

[[['Piña' 'Fresa']
  ['Manzana' 'Achotillo']
  ['Pera' 'Kiwi']]

 [['Aguacate' 'Arándano']
  ['Uva' 'Grosella']
  ['Naranja' 'Pepino']]

 [['Frutilla' 'Ciruela']
  ['Plàtano' 'Coco']
  ['Granadilla' 'Guaba']]

 [['Melon' 'Limon']
  ['Papaya' 'Mango']
  ['Sandìa' 'Cereza']]]


array([['Piña', 'Fresa', 'Manzana']], dtype='<U10')

In [33]:
arreglo_frutas3d.shape

(4, 3, 2)

In [34]:
arreglo_frutas3d[0][0][0]

'Piña'

In [35]:
arreglo_frutas[np.array([0]),np.array([0])]

array([['Piña', 'Manzana']], dtype='<U10')

In [36]:
arreglo_frutas[np.array([0][0]),np.array([0,1])]

array([['Piña', 'Manzana'],
       ['Pera', 'Melon']], dtype='<U10')

In [38]:
arreglo_frutas[np.array([0]),np.array([0]),np.array([0])]

array(['Piña'], dtype='<U10')

In [39]:
arreglo_frutas[np.array([0]),np.array([0]),np.array([1])]

array(['Manzana'], dtype='<U10')

In [43]:
# retornar las frutas que empiecen con p
arreglo_frutas

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon']],

       [['Pera', 'Uva'],
        ['Naranja', 'Papaya']],

       [['Frutilla', 'Plàtano'],
        ['Granadilla', 'Sandìa']]], dtype='<U10')

In [49]:
# arreglo_con_f = arreglo_frutas.char.split()[0] == 'P'

In [12]:
# Mostrar todas las frutas que empiecen con P
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Plàtano','Granadilla','Sandìa']
])

arreglo_frutas2d = np.array([
    ['Piña','Fresa','Manzana','Achotillo','Pera','Kiwi'],
    ['Aguacate','Arándano','Uva','Grosella','Naranja','Pepino'],
    ['Frutilla','Ciruela','Plàtano','Coco','Granadilla','Guaba'],
    ['Melon','Limon','Papaya','Mango','Sandìa','Cereza']
])

listaConP = list(map(lambda x: x[0:1] == 'P',arreglo_frutas.flatten()))
print(arreglo_frutas.flatten()[listaConP])

listaConP1 = list(map(lambda x: x[0:1] == 'P',arreglo_frutas2d.flatten()))
print(arreglo_frutas2d.flatten()[listaConP1])

['Piña' 'Pera' 'Pera' 'Papaya' 'Plàtano']
['Piña' 'Pera' 'Pepino' 'Plàtano' 'Papaya']
